### PR TITLE
[Update] Better AI response

### PR DESCRIPTION
**Pull request by gvoze32**

### CODE REVIEW

**Comment by honestyan** [comment]
Hi @gvoze32  , I really appreciate your work on this! 

Anyway, does this update only restructure the commit messages, or does it also implement semantic conventions, like using : instead of []?

Thanks again for your help!

**Comment by gvoze32** [comment]
Hey, I just updated it and now it's almost like the standard format of Conventional Commits.

The result will be something like:
fix: update script to create daemon.json file and set custom Docker default address pools
fix(custom_docker_size): update debug log output for Docker daemon service rule creation and customization.
fix(custom_docker_size): update debug log output for Docker daemon service rule creation and customization.
feat(install): Create /etc/docker/daemon.json file and set custom Docker default address pools.

**Comment by honestyan** [comment]
> Hey, I just updated it and now it's almost like the standard format of Conventional Commits.
> 
> The result will be something like: fix: update script to create daemon.json file and set custom Docker default address pools fix(custom_docker_size): update debug log output for Docker daemon service rule creation and customization. fix(custom_docker_size): update debug log output for Docker daemon service rule creation and customization. feat(install): Create /etc/docker/daemon.json file and set custom Docker default address pools.

Thanks so much for the effort to switch to semantic commit conventions—I really appreciate it! 🎉

I think the new format looks great, but I’ll need to run some trial and error to test how the updated prompts handle the token/character limitations, especially since GROQ has a specific token limit.

I've merged this update, and I’d like to ask for your help in testing those limitations to ensure everything works smoothly with longer prompts. Let me know if you're available to collaborate on this!

Will release it ASAP. Thanks again for all your hard work! 🚀

**Comment by gvoze32** [comment]
@honestyan

Okay if there are some limitation cases later, I will improve it with a shorter and more concise prompt and open a new pull request.

**Pull request merged**
